name: Build Check

on:
  push

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_BACKEND_URL: 'http://localhost:5272'
          JWT_SECRET: '0yWqXf87FN3E26134S1575irUOmihSLZ'
          BANK_LOOKUP_API_KEY: '0yuBbEMK8LdtPsWQR0Kh6gdTmY5j6x'
          BANK_LOOKUP_SECRET: '0yuBbEMK8LdtPsWQR0Kh6gdTmY5j6x'
