name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - product
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_BACKEND_URL: 'http://localhost:5272'
          JWT_SECRET: '123123123123123123'
          BANK_LOOKUP_API_KEY: '0yuBbEMK8LdtPsWQR0Kh6gdTmY5j6x'
          BANK_LOOKUP_SECRET: '0yuBbEMK8LdtPsWQR0Kh6gdTmY5j6xk'
          CLOUDINARY_CLOUD_NAME: 'fsdf34g34'
          CLOUDINARY_API_KEY: '123123'
          CLOUDINARY_API_SECRET: '3323dfsd-RsH-DMyo'

      
      # - name: Test
      #   run: pnpm test
      #   env:
      #     MONGODB_URI: mongodb://localhost:27017/testdb
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            if [ "${{ github.ref_name }}" == "dev" ]; then
              cd /home/dkmtech/dev-anf-fe/anf-frontend
              git pull origin dev
              git status
              pnpm install --frozen-lockfile
              pnpm build
              pm2 restart dev-anf
            elif [ "${{ github.ref_name }}" == "product" ]; then
              cd /home/dkmtech/anf-frontend
              git pull origin product
              git status
              pnpm install --frozen-lockfile
              pnpm build
              pm2 restart anf
            fi
