name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # services:
    #   mongodb:
    #     image: mongo
    #     ports:
    #       - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0
  
      - name: Install pnpm
        uses: pnpm/action-setup@v2
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_BACKEND_URL: 'http://localhost:5272'
          JWT_SECRET: "0yWqXf87FN3E26134S1575irUOmihSLZ"

      # - name: Test
      #   run: pnpm test
      #   env:
      #     MONGODB_URI: mongodb://localhost:27017/testdb

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/dkmtech/dev-anf-fe/anf-frontend
            git pull origin dev
            git status
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart dev-anf
